// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ClassLibrary2.Models;
[Table("FactSale", Schema = "Fact")]
public class FactSale
{
    public long FactSalesId { get; set; }

    public int DateKey { get; set; }

    public int CustomerKey { get; set; }

    public int ProductKey { get; set; }

    public int StatusKey { get; set; }

    public int OrderIdNk { get; set; }

    public int Quantity { get; set; }

    public decimal TotalPrice { get; set; }
    /*
    public virtual DimCustomer CustomerKeyNavigation { get; set; }

    public virtual DimDate DateKeyNavigation { get; set; }

    public virtual DimProduct ProductKeyNavigation { get; set; }

    public virtual DimStatus StatusKeyNavigation { get; set; }*/
}