// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace SalesAnalytics.Domain.Entities.Dwh.Dimensions
{
    [Table("DimCustomer", Schema = "Dimension")]
    public class DimCustomer
    {
        public int CustomerKey { get; set; }

        public int CustomerIdNk { get; set; }

        public string CustomerName { get; set; }

        public string Email { get; set; }

        public string Phone { get; set; }

        public string City { get; set; }

        public string Country { get; set; }

        //public virtual ICollection<FactSale> FactSales { get; set; } = new List<FactSale>();
    }
}