// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SalesAnalytics.Domain.Entities.Dwh.Dimensions
{
    [Table("DimDate", Schema = "Dimension")]
    public class DimDate
    {
        [Key]
        public int DateKey { get; set; }

        public DateOnly FullDate { get; set; }

        public int Day { get; set; }

        public int Month { get; set; }

        public string MonthName { get; set; }

        public int Quarter { get; set; }

        public int Year { get; set; }

        public string DayOfWeek { get; set; }

        public int DayOfYear { get; set; }

        //public virtual ICollection<FactSale> FactSales { get; set; } = new List<FactSale>();
    }
}