// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace SalesAnalytics.Domain.Entities.Dwh.Dimensions
{
    [Table("DimProduct", Schema = "Dimension")]
    public class DimProduct
    {
        public int ProductKey { get; set; }

        public int ProductIdNk { get; set; }

        public string ProductName { get; set; }

        public string Category { get; set; }

        public decimal? Price { get; set; }

        //public virtual ICollection<FactSale> FactSales { get; set; } = new List<FactSale>();
    }
}