// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace SalesAnalytics.Domain.Entities.Dwh.Dimensions
{
    [Table("DimStatus", Schema = "Dimension")]
    public class DimStatus
    {
        public int StatusKey { get; set; }

        public string StatusName { get; set; }

        //public virtual ICollection<FactSale> FactSales { get; set; } = new List<FactSale>();
    }
}